-- create database bibliotheque;
-- \c bibliotheque;
CREATE TABLE
    tag (
        idTag INT GENERATED BY DEFAULT AS IDENTITY,
        tagName VARCHAR(255),
        PRIMARY KEY (idTag)
    );

CREATE TABLE
    typeAccount (
        idTypeAccount INT GENERATED BY DEFAULT AS IDENTITY,
        accountType VARCHAR(255),
        PRIMARY KEY (idTypeAccount)
    );

CREATE TABLE
    users (
        idUser INT GENERATED BY DEFAULT AS IDENTITY,
        userName VARCHAR(255),
        motDePasse VARCHAR(255),
        idTypeAccount INTEGER REFERENCES typeAccount(idTypeAccount),
        PRIMARY KEY (idUser)
    );

CREATE TABLE categorieAge(
    idCategorieAge INT GENERATED BY DEFAULT AS IDENTITY,
    ageMin INT,
    ageMax INT,
    PRIMARY KEY (idCategorieAge)
);

CREATE TABLE
    livre (
        idLivre INT GENERATED BY DEFAULT AS IDENTITY,
        isbn VARCHAR(255),
        editionDate DATE,
        auteur VARCHAR(255),
        idCategorieAge INTEGER REFERENCES categorieAge(idCategorieAge),
        PRIMARY KEY (idLivre)
    );

CREATE TABLE
    tagLivre (
        idTagLivre INT GENERATED BY DEFAULT AS IDENTITY,
        idLivre INTEGER REFERENCES livre (idLivre),
        idTag INTEGER REFERENCES tag (idTag),
        PRIMARY KEY (idTagLivre)
    );

CREATE TABLE
    exemplaire (
        idExemplaire INT GENERATED BY DEFAULT AS IDENTITY,
        idLivre INTEGER REFERENCES livre (idLivre),
        nbExemplaire INT,
        PRIMARY KEY (idExemplaire)
    );

CREATE TABLE
    profil (
        idProfil INT GENERATED BY DEFAULT AS IDENTITY,
        profilType VARCHAR(255),
        quotaPret INT,
        PRIMARY KEY (idProfil)
    );

CREATE TABLE
    livreProfil (
        idLivreProfil INT GENERATED BY DEFAULT AS IDENTITY,
        idLivre INTEGER REFERENCES livre (idLivre),
        idProfil INTEGER REFERENCES profil (idProfil),
        PRIMARY KEY (idLivreProfil)
    );

CREATE TABLE
    inscription (
        idInscription INT GENERATED BY DEFAULT AS IDENTITY,
        dateDebutAbonnement DATE,
        dateFinAbonnement DATE,
        PRIMARY KEY (idInscription)
    );

CREATE TABLE
    statutAdherent (
        idStatut INT GENERATED BY DEFAULT AS IDENTITY,
        statut VARCHAR(255),
        PRIMARY KEY (idStatut)
    );

CREATE TABLE
    adherent (
        idAdherent INT GENERATED BY DEFAULT AS IDENTITY,
        adherentName VARCHAR(255),
        idProfil INTEGER REFERENCES profil (idProfil),
        idInscription INTEGER REFERENCES inscription (idInscription),
        statut INTEGER REFERENCES statutAdherent (idStatut),
        PRIMARY KEY (idAdherent)
    );

CREATE TABLE
    historiqueStatutAdherent (
        idHistoriqueStatutAdherent INT GENERATED BY DEFAULT AS IDENTITY,
        idStatut INTEGER REFERENCES statutAdherent (idStatut),
        idAdherent INTEGER REFERENCES adherent (idAdherent),
        PRIMARY KEY (idHistoriqueStatutAdherent)
    );

CREATE TABLE
    typePret (
        idTypePret INT GENERATED BY DEFAULT AS IDENTITY,
        typePret VARCHAR(255),
        PRIMARY KEY (idTypePret)
    );

CREATE TABLE
    statutPret (
        idStatut INT GENERATED BY DEFAULT AS IDENTITY,
        statut VARCHAR(255),
        PRIMARY KEY (idStatut)
    );

CREATE TABLE
    pret (
        idPret INT GENERATED BY DEFAULT AS IDENTITY,
        datePret DATE,
        idExemplaire INTEGER REFERENCES exemplaire (idExemplaire),
        idAdherent INTEGER REFERENCES adherent (idAdherent),
        idTypePret INTEGER REFERENCES typePret (idTypePret),
        PRIMARY KEY (idPret)
    );

CREATE TABLE
    HistoriquePret (
        idHistoriquePret INT GENERATED BY DEFAULT AS IDENTITY,
        dateStatut DATE,
        idStatut INTEGER REFERENCES statutPret (idStatut),
        idPret INTEGER REFERENCES pret (idPret),
        PRIMARY KEY (idHistoriquePret)
    );

CREATE TABLE
    prolongementPret (
        idProlongementPret INT GENERATED BY DEFAULT AS IDENTITY,
        duree INT,
        idPret INTEGER REFERENCES pret (idPret),
        PRIMARY KEY (idProlongementPret)
    );

CREATE TABLE
    historiqueCotisation (
        idHistoriqueCotisation INT GENERATED BY DEFAULT AS IDENTITY,
        dateCotisation DATE,
        idAdherent INTEGER REFERENCES adherent (idAdherent),
        PRIMARY KEY (idHistoriqueCotisation)
    );

CREATE TABLE
    historiquePenalite (
        idHistoriquePenalite INT GENERATED BY DEFAULT AS IDENTITY,
        dateDebutPenalite DATE,
        dateFinPenalite DATE,
        PRIMARY KEY (idHistoriquePenalite)
    );

CREATE TABLE
    reservation (
        idReservation INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        idExemplaire INT REFERENCES exemplaire (idExemplaire),
        idAdherent INT REFERENCES adherent (idAdherent),
        dateReservation DATE,
        statut VARCHAR(50), -- en attente, annulée, expirée, confirmée
        expiration DATE
    );